// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

/*
Package go_proto is a generated protocol buffer package.

It is generated from these files:
	account.proto
	common.proto
	login.proto

It has these top-level messages:
	M_1001Tos
	M_1001Toc
	M_1002Tos
	M_1002Toc
	PDeviceInfo
	M_1003Tos
	M_1003Toc
	M_1004Tos
	M_1004Toc
	M_1005Tos
	M_1005Toc
	M_1006Tos
	M_1006Toc
	M_1007Tos
	M_1007Toc
	M_1009Tos
	M_1009Toc
	M_1010Tos
	M_1010Toc
	M_1016Tos
	M_1016Toc
	M_1017Toc
	M_1018Tos
	M_1018Toc
	PNotice
	M_1019Tos
	M_1019Toc
	M_1020Tos
	M_1020Toc
	M_1021Tos
	M_1021Toc
	M_1022Toc
	M_1023Tos
	M_1023Toc
	M_1024Toc
	M_1101Toc
	M_1201Tos
	M_1201Toc
	M_1202Tos
	M_1202Toc
	M_1203Tos
	M_1203Toc
	M_1204Tos
	M_1204Toc
	M_1206Toc
	M_1207Tos
	M_1207Toc
	M_1208Tos
	M_1208Toc
*/
package go_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type M_1001Tos struct {
	ProtoVersion     *uint32      `protobuf:"varint,1,req,name=proto_version,json=protoVersion" json:"proto_version,omitempty"`
	ClientVersion    *string      `protobuf:"bytes,2,req,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	Channel          *string      `protobuf:"bytes,3,req,name=channel" json:"channel,omitempty"`
	AgentId          *uint32      `protobuf:"varint,4,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	FirstOpen        *uint32      `protobuf:"varint,5,opt,name=first_open,json=firstOpen" json:"first_open,omitempty"`
	Device           *PDeviceInfo `protobuf:"bytes,6,opt,name=device" json:"device,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *M_1001Tos) Reset()                    { *m = M_1001Tos{} }
func (m *M_1001Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1001Tos) ProtoMessage()               {}
func (*M_1001Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *M_1001Tos) GetProtoVersion() uint32 {
	if m != nil && m.ProtoVersion != nil {
		return *m.ProtoVersion
	}
	return 0
}

func (m *M_1001Tos) GetClientVersion() string {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return ""
}

func (m *M_1001Tos) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func (m *M_1001Tos) GetAgentId() uint32 {
	if m != nil && m.AgentId != nil {
		return *m.AgentId
	}
	return 0
}

func (m *M_1001Tos) GetFirstOpen() uint32 {
	if m != nil && m.FirstOpen != nil {
		return *m.FirstOpen
	}
	return 0
}

func (m *M_1001Tos) GetDevice() *PDeviceInfo {
	if m != nil {
		return m.Device
	}
	return nil
}

// 服务器端发回的随机码，客户端要再一次md5产生一个新key，取前8位作为前后端加密用的密钥
type M_1001Toc struct {
	ProtoVersion     *uint32 `protobuf:"varint,1,req,name=proto_version,json=protoVersion" json:"proto_version,omitempty"`
	RandomKey        []byte  `protobuf:"bytes,2,req,name=random_key,json=randomKey" json:"random_key,omitempty"`
	RaiderStatus     *uint32 `protobuf:"varint,3,opt,name=raider_status,json=raiderStatus" json:"raider_status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1001Toc) Reset()                    { *m = M_1001Toc{} }
func (m *M_1001Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1001Toc) ProtoMessage()               {}
func (*M_1001Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *M_1001Toc) GetProtoVersion() uint32 {
	if m != nil && m.ProtoVersion != nil {
		return *m.ProtoVersion
	}
	return 0
}

func (m *M_1001Toc) GetRandomKey() []byte {
	if m != nil {
		return m.RandomKey
	}
	return nil
}

func (m *M_1001Toc) GetRaiderStatus() uint32 {
	if m != nil && m.RaiderStatus != nil {
		return *m.RaiderStatus
	}
	return 0
}

// 上传用户设备信息,前端不发
type M_1002Tos struct {
	ClientInfo       *PDeviceInfo `protobuf:"bytes,1,req,name=client_info,json=clientInfo" json:"client_info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *M_1002Tos) Reset()                    { *m = M_1002Tos{} }
func (m *M_1002Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1002Tos) ProtoMessage()               {}
func (*M_1002Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *M_1002Tos) GetClientInfo() *PDeviceInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

type M_1002Toc struct {
	Installed        *bool  `protobuf:"varint,1,req,name=installed" json:"installed,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1002Toc) Reset()                    { *m = M_1002Toc{} }
func (m *M_1002Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1002Toc) ProtoMessage()               {}
func (*M_1002Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *M_1002Toc) GetInstalled() bool {
	if m != nil && m.Installed != nil {
		return *m.Installed
	}
	return false
}

// 用户设备信息
type PDeviceInfo struct {
	Platform         *string `protobuf:"bytes,1,req,name=platform" json:"platform,omitempty"`
	LocInfo          *string `protobuf:"bytes,2,opt,name=loc_info,json=locInfo" json:"loc_info,omitempty"`
	OsVersion        *string `protobuf:"bytes,3,opt,name=os_version,json=osVersion" json:"os_version,omitempty"`
	OsLang           *string `protobuf:"bytes,4,opt,name=os_lang,json=osLang" json:"os_lang,omitempty"`
	Resolution       *string `protobuf:"bytes,5,opt,name=resolution" json:"resolution,omitempty"`
	Model            *string `protobuf:"bytes,6,opt,name=model" json:"model,omitempty"`
	ConnectType      *string `protobuf:"bytes,7,opt,name=connect_type,json=connectType" json:"connect_type,omitempty"`
	DeviceId         *string `protobuf:"bytes,9,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PDeviceInfo) Reset()                    { *m = PDeviceInfo{} }
func (m *PDeviceInfo) String() string            { return proto.CompactTextString(m) }
func (*PDeviceInfo) ProtoMessage()               {}
func (*PDeviceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PDeviceInfo) GetPlatform() string {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return ""
}

func (m *PDeviceInfo) GetLocInfo() string {
	if m != nil && m.LocInfo != nil {
		return *m.LocInfo
	}
	return ""
}

func (m *PDeviceInfo) GetOsVersion() string {
	if m != nil && m.OsVersion != nil {
		return *m.OsVersion
	}
	return ""
}

func (m *PDeviceInfo) GetOsLang() string {
	if m != nil && m.OsLang != nil {
		return *m.OsLang
	}
	return ""
}

func (m *PDeviceInfo) GetResolution() string {
	if m != nil && m.Resolution != nil {
		return *m.Resolution
	}
	return ""
}

func (m *PDeviceInfo) GetModel() string {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return ""
}

func (m *PDeviceInfo) GetConnectType() string {
	if m != nil && m.ConnectType != nil {
		return *m.ConnectType
	}
	return ""
}

func (m *PDeviceInfo) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

// 登录,前端把明文密码md5哈希一次，然后des加密后得到密码
type M_1003Tos struct {
	Username         *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Password         []byte  `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	Inviter          *int32  `protobuf:"varint,3,opt,name=inviter,def=0" json:"inviter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1003Tos) Reset()                    { *m = M_1003Tos{} }
func (m *M_1003Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1003Tos) ProtoMessage()               {}
func (*M_1003Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

const Default_M_1003Tos_Inviter int32 = 0

func (m *M_1003Tos) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *M_1003Tos) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *M_1003Tos) GetInviter() int32 {
	if m != nil && m.Inviter != nil {
		return *m.Inviter
	}
	return Default_M_1003Tos_Inviter
}

// 返回登录游戏服务器信息
type M_1003Toc struct {
	GameserverAddr   *string `protobuf:"bytes,1,req,name=gameserver_addr,json=gameserverAddr" json:"gameserver_addr,omitempty"`
	GameserverPort   *uint32 `protobuf:"varint,2,req,name=gameserver_port,json=gameserverPort" json:"gameserver_port,omitempty"`
	AuthKey          []byte  `protobuf:"bytes,3,req,name=auth_key,json=authKey" json:"auth_key,omitempty"`
	RoleId           *uint32 `protobuf:"varint,4,req,name=role_id,json=roleId" json:"role_id,omitempty"`
	BlockLeftTime    *int32  `protobuf:"varint,5,opt,name=block_left_time,json=blockLeftTime" json:"block_left_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1003Toc) Reset()                    { *m = M_1003Toc{} }
func (m *M_1003Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1003Toc) ProtoMessage()               {}
func (*M_1003Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *M_1003Toc) GetGameserverAddr() string {
	if m != nil && m.GameserverAddr != nil {
		return *m.GameserverAddr
	}
	return ""
}

func (m *M_1003Toc) GetGameserverPort() uint32 {
	if m != nil && m.GameserverPort != nil {
		return *m.GameserverPort
	}
	return 0
}

func (m *M_1003Toc) GetAuthKey() []byte {
	if m != nil {
		return m.AuthKey
	}
	return nil
}

func (m *M_1003Toc) GetRoleId() uint32 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

func (m *M_1003Toc) GetBlockLeftTime() int32 {
	if m != nil && m.BlockLeftTime != nil {
		return *m.BlockLeftTime
	}
	return 0
}

// -------------------废弃协议------------------------------
// 玩家注册，前端把明文密码md5哈希一次，然后des加密后得到密码, 苹果审核专用
type M_1004Tos struct {
	Username         []byte       `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	NickName         []byte       `protobuf:"bytes,2,req,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	Password         []byte       `protobuf:"bytes,3,req,name=password" json:"password,omitempty"`
	CheckCode        []byte       `protobuf:"bytes,4,opt,name=check_code,json=checkCode" json:"check_code,omitempty"`
	Device           *PDeviceInfo `protobuf:"bytes,5,opt,name=device" json:"device,omitempty"`
	Channel          *uint32      `protobuf:"varint,6,req,name=channel" json:"channel,omitempty"`
	InstallNo        *string      `protobuf:"bytes,7,opt,name=install_no,json=installNo" json:"install_no,omitempty"`
	CpsId            *uint32      `protobuf:"varint,8,opt,name=cps_id,json=cpsId" json:"cps_id,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *M_1004Tos) Reset()                    { *m = M_1004Tos{} }
func (m *M_1004Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1004Tos) ProtoMessage()               {}
func (*M_1004Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *M_1004Tos) GetUsername() []byte {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *M_1004Tos) GetNickName() []byte {
	if m != nil {
		return m.NickName
	}
	return nil
}

func (m *M_1004Tos) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *M_1004Tos) GetCheckCode() []byte {
	if m != nil {
		return m.CheckCode
	}
	return nil
}

func (m *M_1004Tos) GetDevice() *PDeviceInfo {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *M_1004Tos) GetChannel() uint32 {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return 0
}

func (m *M_1004Tos) GetInstallNo() string {
	if m != nil && m.InstallNo != nil {
		return *m.InstallNo
	}
	return ""
}

func (m *M_1004Tos) GetCpsId() uint32 {
	if m != nil && m.CpsId != nil {
		return *m.CpsId
	}
	return 0
}

// -------------------废弃协议------------------------------
// 注册成功 返回用户名密码 可以用这个信息登录
type M_1004Toc struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1004Toc) Reset()                    { *m = M_1004Toc{} }
func (m *M_1004Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1004Toc) ProtoMessage()               {}
func (*M_1004Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// -------------------废弃协议------------------------------
// 申请游客帐号，苹果审核专用
type M_1005Tos struct {
	PlatformName     *string `protobuf:"bytes,1,opt,name=platform_name,json=platformName" json:"platform_name,omitempty"`
	Channel          *string `protobuf:"bytes,2,opt,name=channel" json:"channel,omitempty"`
	PlatformSys      *string `protobuf:"bytes,3,opt,name=platform_sys,json=platformSys" json:"platform_sys,omitempty"`
	InstallNo        *string `protobuf:"bytes,4,opt,name=install_no,json=installNo" json:"install_no,omitempty"`
	CpsId            *uint32 `protobuf:"varint,5,opt,name=cps_id,json=cpsId" json:"cps_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1005Tos) Reset()                    { *m = M_1005Tos{} }
func (m *M_1005Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1005Tos) ProtoMessage()               {}
func (*M_1005Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *M_1005Tos) GetPlatformName() string {
	if m != nil && m.PlatformName != nil {
		return *m.PlatformName
	}
	return ""
}

func (m *M_1005Tos) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func (m *M_1005Tos) GetPlatformSys() string {
	if m != nil && m.PlatformSys != nil {
		return *m.PlatformSys
	}
	return ""
}

func (m *M_1005Tos) GetInstallNo() string {
	if m != nil && m.InstallNo != nil {
		return *m.InstallNo
	}
	return ""
}

func (m *M_1005Tos) GetCpsId() uint32 {
	if m != nil && m.CpsId != nil {
		return *m.CpsId
	}
	return 0
}

// -------------------废弃协议------------------------------
type M_1005Toc struct {
	Username         []byte `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Password         []byte `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1005Toc) Reset()                    { *m = M_1005Toc{} }
func (m *M_1005Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1005Toc) ProtoMessage()               {}
func (*M_1005Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *M_1005Toc) GetUsername() []byte {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *M_1005Toc) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

// 获取手机注册验证码
type M_1006Tos struct {
	Phone            *string `protobuf:"bytes,1,req,name=phone" json:"phone,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1006Tos) Reset()                    { *m = M_1006Tos{} }
func (m *M_1006Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1006Tos) ProtoMessage()               {}
func (*M_1006Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *M_1006Tos) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

// 错误发错误码
type M_1006Toc struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1006Toc) Reset()                    { *m = M_1006Toc{} }
func (m *M_1006Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1006Toc) ProtoMessage()               {}
func (*M_1006Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

// 电话号码注册
type M_1007Tos struct {
	Phone            *string      `protobuf:"bytes,1,req,name=phone" json:"phone,omitempty"`
	Password         []byte       `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	CheckCode        *string      `protobuf:"bytes,3,req,name=check_code,json=checkCode" json:"check_code,omitempty"`
	Device           *PDeviceInfo `protobuf:"bytes,4,opt,name=device" json:"device,omitempty"`
	Channel          *uint32      `protobuf:"varint,5,req,name=channel" json:"channel,omitempty"`
	InstallNo        *string      `protobuf:"bytes,6,opt,name=install_no,json=installNo" json:"install_no,omitempty"`
	CpsId            *uint32      `protobuf:"varint,7,opt,name=cps_id,json=cpsId" json:"cps_id,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *M_1007Tos) Reset()                    { *m = M_1007Tos{} }
func (m *M_1007Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1007Tos) ProtoMessage()               {}
func (*M_1007Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *M_1007Tos) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *M_1007Tos) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *M_1007Tos) GetCheckCode() string {
	if m != nil && m.CheckCode != nil {
		return *m.CheckCode
	}
	return ""
}

func (m *M_1007Tos) GetDevice() *PDeviceInfo {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *M_1007Tos) GetChannel() uint32 {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return 0
}

func (m *M_1007Tos) GetInstallNo() string {
	if m != nil && m.InstallNo != nil {
		return *m.InstallNo
	}
	return ""
}

func (m *M_1007Tos) GetCpsId() uint32 {
	if m != nil && m.CpsId != nil {
		return *m.CpsId
	}
	return 0
}

// 注册成功，失败发错误码
type M_1007Toc struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1007Toc) Reset()                    { *m = M_1007Toc{} }
func (m *M_1007Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1007Toc) ProtoMessage()               {}
func (*M_1007Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

// 找回密码前获取验证码
type M_1009Tos struct {
	Phone            *string `protobuf:"bytes,1,req,name=phone" json:"phone,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1009Tos) Reset()                    { *m = M_1009Tos{} }
func (m *M_1009Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1009Tos) ProtoMessage()               {}
func (*M_1009Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *M_1009Tos) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

type M_1009Toc struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1009Toc) Reset()                    { *m = M_1009Toc{} }
func (m *M_1009Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1009Toc) ProtoMessage()               {}
func (*M_1009Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

// 修改密码
type M_1010Tos struct {
	Phone            *string `protobuf:"bytes,1,req,name=phone" json:"phone,omitempty"`
	Code             *uint32 `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	Password         []byte  `protobuf:"bytes,3,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1010Tos) Reset()                    { *m = M_1010Tos{} }
func (m *M_1010Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1010Tos) ProtoMessage()               {}
func (*M_1010Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *M_1010Tos) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *M_1010Tos) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *M_1010Tos) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type M_1010Toc struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1010Toc) Reset()                    { *m = M_1010Toc{} }
func (m *M_1010Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1010Toc) ProtoMessage()               {}
func (*M_1010Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type M_1016Tos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1016Tos) Reset()                    { *m = M_1016Tos{} }
func (m *M_1016Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1016Tos) ProtoMessage()               {}
func (*M_1016Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type M_1016Toc struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1016Toc) Reset()                    { *m = M_1016Toc{} }
func (m *M_1016Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1016Toc) ProtoMessage()               {}
func (*M_1016Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

// 客户端接收到这个信息，服务器端已经关闭tcp连接，客户端要重新开始新的网络连接
type M_1017Toc struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1017Toc) Reset()                    { *m = M_1017Toc{} }
func (m *M_1017Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1017Toc) ProtoMessage()               {}
func (*M_1017Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

// 登陆界面公告
type M_1018Tos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1018Tos) Reset()                    { *m = M_1018Tos{} }
func (m *M_1018Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1018Tos) ProtoMessage()               {}
func (*M_1018Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type M_1018Toc struct {
	Notices          []*PNotice `protobuf:"bytes,1,rep,name=notices" json:"notices,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *M_1018Toc) Reset()                    { *m = M_1018Toc{} }
func (m *M_1018Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1018Toc) ProtoMessage()               {}
func (*M_1018Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *M_1018Toc) GetNotices() []*PNotice {
	if m != nil {
		return m.Notices
	}
	return nil
}

type PNotice struct {
	Id               *uint32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Title            []byte   `protobuf:"bytes,2,req,name=title" json:"title,omitempty"`
	Content          []byte   `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	Time             []uint32 `protobuf:"varint,4,rep,name=time" json:"time,omitempty"`
	No               []uint32 `protobuf:"varint,5,rep,name=no" json:"no,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PNotice) Reset()                    { *m = PNotice{} }
func (m *PNotice) String() string            { return proto.CompactTextString(m) }
func (*PNotice) ProtoMessage()               {}
func (*PNotice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *PNotice) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PNotice) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *PNotice) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *PNotice) GetTime() []uint32 {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *PNotice) GetNo() []uint32 {
	if m != nil {
		return m.No
	}
	return nil
}

// 微信登陆
type M_1019Tos struct {
	Code             []byte       `protobuf:"bytes,1,req,name=code" json:"code,omitempty"`
	Device           *PDeviceInfo `protobuf:"bytes,2,opt,name=device" json:"device,omitempty"`
	Channel          *uint32      `protobuf:"varint,3,req,name=channel" json:"channel,omitempty"`
	InstallNo        *string      `protobuf:"bytes,4,opt,name=install_no,json=installNo" json:"install_no,omitempty"`
	CpsId            *int32       `protobuf:"varint,5,req,name=cps_id,json=cpsId" json:"cps_id,omitempty"`
	Inviter          *int32       `protobuf:"varint,6,req,name=inviter" json:"inviter,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *M_1019Tos) Reset()                    { *m = M_1019Tos{} }
func (m *M_1019Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1019Tos) ProtoMessage()               {}
func (*M_1019Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *M_1019Tos) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *M_1019Tos) GetDevice() *PDeviceInfo {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *M_1019Tos) GetChannel() uint32 {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return 0
}

func (m *M_1019Tos) GetInstallNo() string {
	if m != nil && m.InstallNo != nil {
		return *m.InstallNo
	}
	return ""
}

func (m *M_1019Tos) GetCpsId() int32 {
	if m != nil && m.CpsId != nil {
		return *m.CpsId
	}
	return 0
}

func (m *M_1019Tos) GetInviter() int32 {
	if m != nil && m.Inviter != nil {
		return *m.Inviter
	}
	return 0
}

// 错误发错误码， 收到这个信息表示微信授权成功，可以登陆游戏
type M_1019Toc struct {
	GameserverAddr   *string `protobuf:"bytes,1,req,name=gameserver_addr,json=gameserverAddr" json:"gameserver_addr,omitempty"`
	GameserverPort   *uint32 `protobuf:"varint,2,req,name=gameserver_port,json=gameserverPort" json:"gameserver_port,omitempty"`
	AuthKey          []byte  `protobuf:"bytes,3,req,name=auth_key,json=authKey" json:"auth_key,omitempty"`
	RoleId           *uint32 `protobuf:"varint,4,req,name=role_id,json=roleId" json:"role_id,omitempty"`
	Username         *string `protobuf:"bytes,5,req,name=username" json:"username,omitempty"`
	Password         []byte  `protobuf:"bytes,6,req,name=password" json:"password,omitempty"`
	Level            *uint32 `protobuf:"varint,7,req,name=level" json:"level,omitempty"`
	BlockLeftTime    *int32  `protobuf:"varint,8,opt,name=block_left_time,json=blockLeftTime" json:"block_left_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1019Toc) Reset()                    { *m = M_1019Toc{} }
func (m *M_1019Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1019Toc) ProtoMessage()               {}
func (*M_1019Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *M_1019Toc) GetGameserverAddr() string {
	if m != nil && m.GameserverAddr != nil {
		return *m.GameserverAddr
	}
	return ""
}

func (m *M_1019Toc) GetGameserverPort() uint32 {
	if m != nil && m.GameserverPort != nil {
		return *m.GameserverPort
	}
	return 0
}

func (m *M_1019Toc) GetAuthKey() []byte {
	if m != nil {
		return m.AuthKey
	}
	return nil
}

func (m *M_1019Toc) GetRoleId() uint32 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

func (m *M_1019Toc) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *M_1019Toc) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *M_1019Toc) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *M_1019Toc) GetBlockLeftTime() int32 {
	if m != nil && m.BlockLeftTime != nil {
		return *m.BlockLeftTime
	}
	return 0
}

// 检查帐号是否已经注册
type M_1020Tos struct {
	Username         []byte `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1020Tos) Reset()                    { *m = M_1020Tos{} }
func (m *M_1020Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1020Tos) ProtoMessage()               {}
func (*M_1020Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *M_1020Tos) GetUsername() []byte {
	if m != nil {
		return m.Username
	}
	return nil
}

//
type M_1020Toc struct {
	Flag             *bool  `protobuf:"varint,1,req,name=flag" json:"flag,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1020Toc) Reset()                    { *m = M_1020Toc{} }
func (m *M_1020Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1020Toc) ProtoMessage()               {}
func (*M_1020Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *M_1020Toc) GetFlag() bool {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return false
}

// 申请二维码
// 如果遇到网络断开的情况，要重新建立连接
type M_1021Tos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1021Tos) Reset()                    { *m = M_1021Tos{} }
func (m *M_1021Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1021Tos) ProtoMessage()               {}
func (*M_1021Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

type M_1021Toc struct {
	Url              *string `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1021Toc) Reset()                    { *m = M_1021Toc{} }
func (m *M_1021Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1021Toc) ProtoMessage()               {}
func (*M_1021Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *M_1021Toc) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

// 扫描二维码后， 收到这个信息表示微信授权成功，可以登陆游戏
type M_1022Toc struct {
	GameserverAddr   *string `protobuf:"bytes,1,req,name=gameserver_addr,json=gameserverAddr" json:"gameserver_addr,omitempty"`
	GameserverPort   *uint32 `protobuf:"varint,2,req,name=gameserver_port,json=gameserverPort" json:"gameserver_port,omitempty"`
	AuthKey          []byte  `protobuf:"bytes,3,req,name=auth_key,json=authKey" json:"auth_key,omitempty"`
	RoleId           *uint32 `protobuf:"varint,4,req,name=role_id,json=roleId" json:"role_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1022Toc) Reset()                    { *m = M_1022Toc{} }
func (m *M_1022Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1022Toc) ProtoMessage()               {}
func (*M_1022Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *M_1022Toc) GetGameserverAddr() string {
	if m != nil && m.GameserverAddr != nil {
		return *m.GameserverAddr
	}
	return ""
}

func (m *M_1022Toc) GetGameserverPort() uint32 {
	if m != nil && m.GameserverPort != nil {
		return *m.GameserverPort
	}
	return 0
}

func (m *M_1022Toc) GetAuthKey() []byte {
	if m != nil {
		return m.AuthKey
	}
	return nil
}

func (m *M_1022Toc) GetRoleId() uint32 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

// 新：网页显示二维码
// 如果遇到网络断开的情况，要重新建立连接
type M_1023Tos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1023Tos) Reset()                    { *m = M_1023Tos{} }
func (m *M_1023Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1023Tos) ProtoMessage()               {}
func (*M_1023Tos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

type M_1023Toc struct {
	Url              *string `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1023Toc) Reset()                    { *m = M_1023Toc{} }
func (m *M_1023Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1023Toc) ProtoMessage()               {}
func (*M_1023Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *M_1023Toc) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

// 新：扫描二维码后， 收到这个信息表示微信授权成功，可以登陆游戏
type M_1024Toc struct {
	GameserverAddr   *string `protobuf:"bytes,1,req,name=gameserver_addr,json=gameserverAddr" json:"gameserver_addr,omitempty"`
	GameserverPort   *uint32 `protobuf:"varint,2,req,name=gameserver_port,json=gameserverPort" json:"gameserver_port,omitempty"`
	AuthKey          []byte  `protobuf:"bytes,3,req,name=auth_key,json=authKey" json:"auth_key,omitempty"`
	RoleId           *uint32 `protobuf:"varint,4,req,name=role_id,json=roleId" json:"role_id,omitempty"`
	BlockLeftTime    *int32  `protobuf:"varint,5,opt,name=block_left_time,json=blockLeftTime" json:"block_left_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1024Toc) Reset()                    { *m = M_1024Toc{} }
func (m *M_1024Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1024Toc) ProtoMessage()               {}
func (*M_1024Toc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *M_1024Toc) GetGameserverAddr() string {
	if m != nil && m.GameserverAddr != nil {
		return *m.GameserverAddr
	}
	return ""
}

func (m *M_1024Toc) GetGameserverPort() uint32 {
	if m != nil && m.GameserverPort != nil {
		return *m.GameserverPort
	}
	return 0
}

func (m *M_1024Toc) GetAuthKey() []byte {
	if m != nil {
		return m.AuthKey
	}
	return nil
}

func (m *M_1024Toc) GetRoleId() uint32 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

func (m *M_1024Toc) GetBlockLeftTime() int32 {
	if m != nil && m.BlockLeftTime != nil {
		return *m.BlockLeftTime
	}
	return 0
}

func init() {
	proto.RegisterType((*M_1001Tos)(nil), "go_proto.m_1001_tos")
	proto.RegisterType((*M_1001Toc)(nil), "go_proto.m_1001_toc")
	proto.RegisterType((*M_1002Tos)(nil), "go_proto.m_1002_tos")
	proto.RegisterType((*M_1002Toc)(nil), "go_proto.m_1002_toc")
	proto.RegisterType((*PDeviceInfo)(nil), "go_proto.p_device_info")
	proto.RegisterType((*M_1003Tos)(nil), "go_proto.m_1003_tos")
	proto.RegisterType((*M_1003Toc)(nil), "go_proto.m_1003_toc")
	proto.RegisterType((*M_1004Tos)(nil), "go_proto.m_1004_tos")
	proto.RegisterType((*M_1004Toc)(nil), "go_proto.m_1004_toc")
	proto.RegisterType((*M_1005Tos)(nil), "go_proto.m_1005_tos")
	proto.RegisterType((*M_1005Toc)(nil), "go_proto.m_1005_toc")
	proto.RegisterType((*M_1006Tos)(nil), "go_proto.m_1006_tos")
	proto.RegisterType((*M_1006Toc)(nil), "go_proto.m_1006_toc")
	proto.RegisterType((*M_1007Tos)(nil), "go_proto.m_1007_tos")
	proto.RegisterType((*M_1007Toc)(nil), "go_proto.m_1007_toc")
	proto.RegisterType((*M_1009Tos)(nil), "go_proto.m_1009_tos")
	proto.RegisterType((*M_1009Toc)(nil), "go_proto.m_1009_toc")
	proto.RegisterType((*M_1010Tos)(nil), "go_proto.m_1010_tos")
	proto.RegisterType((*M_1010Toc)(nil), "go_proto.m_1010_toc")
	proto.RegisterType((*M_1016Tos)(nil), "go_proto.m_1016_tos")
	proto.RegisterType((*M_1016Toc)(nil), "go_proto.m_1016_toc")
	proto.RegisterType((*M_1017Toc)(nil), "go_proto.m_1017_toc")
	proto.RegisterType((*M_1018Tos)(nil), "go_proto.m_1018_tos")
	proto.RegisterType((*M_1018Toc)(nil), "go_proto.m_1018_toc")
	proto.RegisterType((*PNotice)(nil), "go_proto.p_notice")
	proto.RegisterType((*M_1019Tos)(nil), "go_proto.m_1019_tos")
	proto.RegisterType((*M_1019Toc)(nil), "go_proto.m_1019_toc")
	proto.RegisterType((*M_1020Tos)(nil), "go_proto.m_1020_tos")
	proto.RegisterType((*M_1020Toc)(nil), "go_proto.m_1020_toc")
	proto.RegisterType((*M_1021Tos)(nil), "go_proto.m_1021_tos")
	proto.RegisterType((*M_1021Toc)(nil), "go_proto.m_1021_toc")
	proto.RegisterType((*M_1022Toc)(nil), "go_proto.m_1022_toc")
	proto.RegisterType((*M_1023Tos)(nil), "go_proto.m_1023_tos")
	proto.RegisterType((*M_1023Toc)(nil), "go_proto.m_1023_toc")
	proto.RegisterType((*M_1024Toc)(nil), "go_proto.m_1024_toc")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1040 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x51, 0x6f, 0xe4, 0x34,
	0x10, 0xd6, 0x66, 0x9b, 0xdd, 0xcd, 0x74, 0xb7, 0x87, 0xac, 0xa2, 0x86, 0x2b, 0x3d, 0xed, 0x05,
	0x01, 0x2b, 0x84, 0x4a, 0xbb, 0x3d, 0xae, 0x77, 0xf7, 0x86, 0x40, 0x48, 0x15, 0xa7, 0x03, 0xe5,
	0x4e, 0xbc, 0x46, 0xc1, 0xf6, 0x6e, 0xa3, 0x66, 0xed, 0x28, 0xf6, 0x16, 0xed, 0x23, 0x6f, 0x3c,
	0xf3, 0x1b, 0xf8, 0x15, 0xf0, 0x5b, 0xe0, 0x57, 0xf0, 0x03, 0x90, 0xc7, 0x76, 0x9a, 0x56, 0x6d,
	0xe8, 0xbd, 0x1d, 0x6f, 0x99, 0xcf, 0xe3, 0xf1, 0xcc, 0x37, 0xdf, 0xd8, 0x81, 0x49, 0x4e, 0xa9,
	0x5c, 0x0b, 0x7d, 0x58, 0xd5, 0x52, 0x4b, 0x32, 0x5a, 0xca, 0x0c, 0xbf, 0x92, 0xbf, 0x7a, 0x00,
	0xab, 0xec, 0xf8, 0xe8, 0xe8, 0x38, 0xd3, 0x52, 0x91, 0x8f, 0x60, 0x82, 0x78, 0x76, 0xc9, 0x6b,
	0x55, 0x48, 0x11, 0xf7, 0xa6, 0xc1, 0x6c, 0x92, 0x8e, 0x11, 0xfc, 0xd1, 0x62, 0xe4, 0x63, 0xd8,
	0xa1, 0x65, 0xc1, 0x85, 0x6e, 0xbc, 0x82, 0x69, 0x30, 0x8b, 0xd2, 0x89, 0x45, 0xbd, 0x5b, 0x0c,
	0x43, 0x7a, 0x9e, 0x0b, 0xc1, 0xcb, 0xb8, 0x8f, 0xeb, 0xde, 0x24, 0x1f, 0xc0, 0x28, 0x5f, 0x9a,
	0xfd, 0x05, 0x8b, 0xb7, 0xa6, 0xbd, 0xd9, 0x24, 0x1d, 0xa2, 0x7d, 0xc6, 0xc8, 0x01, 0xc0, 0xa2,
	0xa8, 0x95, 0xce, 0x64, 0xc5, 0x45, 0x1c, 0xe2, 0x62, 0x84, 0xc8, 0xf7, 0x15, 0x17, 0xe4, 0x0b,
	0x18, 0x30, 0x7e, 0x59, 0x50, 0x1e, 0x0f, 0xa6, 0xbd, 0xd9, 0xf6, 0x7c, 0xef, 0xd0, 0x57, 0x72,
	0x58, 0x65, 0x76, 0x25, 0x2b, 0xc4, 0x42, 0xa6, 0xce, 0x2d, 0x59, 0xb7, 0xca, 0xa3, 0xf7, 0x2b,
	0xef, 0x00, 0xa0, 0xce, 0x05, 0x93, 0xab, 0xec, 0x82, 0x6f, 0xb0, 0xb4, 0x71, 0x1a, 0x59, 0xe4,
	0x3b, 0xbe, 0x31, 0x31, 0xea, 0xbc, 0x60, 0xbc, 0xce, 0x94, 0xce, 0xf5, 0x5a, 0xc5, 0x7d, 0x4c,
	0x72, 0x6c, 0xc1, 0xd7, 0x88, 0x25, 0xdf, 0xba, 0x63, 0xe7, 0xc8, 0xea, 0x33, 0xd8, 0x76, 0x84,
	0x99, 0xdc, 0xf0, 0xd0, 0x8e, 0xd4, 0xc1, 0xfa, 0x9e, 0x89, 0x85, 0x4c, 0x3e, 0x6b, 0xc5, 0xa1,
	0xe4, 0x43, 0x88, 0x0a, 0xa1, 0x74, 0x5e, 0x96, 0x9c, 0x61, 0x94, 0x51, 0x7a, 0x05, 0x24, 0xff,
	0xf4, 0x60, 0x72, 0x2d, 0x12, 0x79, 0x08, 0xa3, 0xaa, 0xcc, 0xf5, 0x42, 0xd6, 0x2b, 0x74, 0x8f,
	0xd2, 0xc6, 0x36, 0x3d, 0x28, 0x25, 0xb5, 0x09, 0x05, 0xd3, 0x9e, 0x69, 0x4f, 0x29, 0xa9, 0x39,
	0xd4, 0x10, 0x20, 0x55, 0x43, 0x51, 0x1f, 0x17, 0x23, 0xa9, 0x3c, 0x3f, 0x7b, 0x30, 0x94, 0x2a,
	0x2b, 0x73, 0xb1, 0xc4, 0xe6, 0x45, 0xe9, 0x40, 0xaa, 0x97, 0xb9, 0x58, 0x92, 0x47, 0x00, 0x35,
	0x57, 0xb2, 0x5c, 0x6b, 0xb3, 0x2f, 0xc4, 0xb5, 0x16, 0x42, 0x76, 0x21, 0x5c, 0x49, 0xc6, 0x4b,
	0xec, 0x5d, 0x94, 0x5a, 0x83, 0x3c, 0x86, 0x31, 0x95, 0x42, 0x70, 0xaa, 0x33, 0xbd, 0xa9, 0x78,
	0x3c, 0xc4, 0xc5, 0x6d, 0x87, 0xbd, 0xd9, 0x54, 0x9c, 0xec, 0x43, 0xe4, 0xcb, 0x62, 0x71, 0x84,
	0xeb, 0x23, 0x0b, 0x9c, 0xb1, 0x24, 0x77, 0x14, 0x9d, 0x20, 0xd5, 0x0f, 0x61, 0xb4, 0x56, 0xbc,
	0x16, 0xf9, 0x8a, 0xfb, 0x92, 0xbd, 0x8d, 0x74, 0xe4, 0x4a, 0xfd, 0x2c, 0x6b, 0xe6, 0xda, 0xda,
	0xd8, 0x64, 0x1f, 0x86, 0x85, 0xb8, 0x2c, 0x34, 0xaf, 0xb1, 0xe0, 0xf0, 0x45, 0xef, 0x28, 0xf5,
	0x48, 0xf2, 0x47, 0xaf, 0x75, 0x06, 0x25, 0x9f, 0xc2, 0x83, 0x65, 0xbe, 0xe2, 0x8a, 0xd7, 0x97,
	0xbc, 0xce, 0x72, 0xc6, 0x6a, 0x77, 0xd4, 0xce, 0x15, 0xfc, 0x15, 0x63, 0xf5, 0x0d, 0xc7, 0x4a,
	0xd6, 0x1a, 0xcf, 0x9d, 0xb4, 0x1d, 0x7f, 0x90, 0xb5, 0xc6, 0x81, 0x58, 0xeb, 0x73, 0x14, 0x5c,
	0x1f, 0x33, 0x1b, 0x1a, 0xdb, 0xc8, 0x6d, 0x0f, 0x86, 0xb5, 0x2c, 0xb9, 0x1d, 0x15, 0xb3, 0x77,
	0x60, 0xcc, 0x33, 0x46, 0x3e, 0x81, 0x07, 0x3f, 0x95, 0x92, 0x5e, 0x64, 0x25, 0x5f, 0xe8, 0x4c,
	0x17, 0x2b, 0x8e, 0x94, 0x87, 0xe9, 0x04, 0xe1, 0x97, 0x7c, 0xa1, 0xdf, 0x14, 0x2b, 0x9e, 0xfc,
	0x12, 0xb8, 0xe4, 0x9f, 0xdc, 0x4a, 0xd0, 0xb8, 0x45, 0xd0, 0x3e, 0x44, 0xa2, 0xa0, 0x17, 0x19,
	0x2e, 0x3a, 0x86, 0x0c, 0xf0, 0xea, 0x26, 0x7b, 0xfd, 0x1b, 0xec, 0x1d, 0x00, 0xd0, 0x73, 0x4e,
	0x2f, 0x32, 0x2a, 0x19, 0x47, 0x55, 0x8c, 0xd3, 0x08, 0x91, 0xaf, 0x25, 0xe3, 0xad, 0xa9, 0x0d,
	0xef, 0x35, 0xb5, 0xed, 0xab, 0x63, 0x80, 0x45, 0x37, 0x57, 0xc7, 0x01, 0x80, 0x53, 0x7c, 0x26,
	0xa4, 0xd3, 0x8a, 0x9f, 0x81, 0x57, 0x92, 0xbc, 0x0f, 0x03, 0x5a, 0x29, 0x43, 0xd6, 0x08, 0xa7,
	0x32, 0xa4, 0x95, 0x3a, 0x63, 0xc9, 0xb8, 0x45, 0x01, 0x4d, 0x7e, 0xf7, 0xed, 0xfc, 0xb2, 0xb9,
	0xf3, 0xdc, 0x54, 0x64, 0x8e, 0x16, 0x13, 0x75, 0xec, 0x41, 0xac, 0xbe, 0x95, 0x91, 0x9b, 0x16,
	0x9f, 0xd1, 0x63, 0x68, 0x3c, 0x33, 0xb5, 0x51, 0x6e, 0x5e, 0xb6, 0x3d, 0xf6, 0x7a, 0xa3, 0x6e,
	0x24, 0xbd, 0x75, 0x77, 0xd2, 0x61, 0x3b, 0xe9, 0x6f, 0x5a, 0x59, 0xd2, 0xce, 0xbe, 0x75, 0x08,
	0x3b, 0x49, 0x5c, 0x94, 0xa7, 0x58, 0xeb, 0x2e, 0x84, 0xd5, 0xb9, 0x14, 0x7e, 0x36, 0xac, 0xd1,
	0xd0, 0xf3, 0x14, 0xe9, 0xf9, 0xdb, 0xd3, 0x73, 0x7a, 0xf7, 0x96, 0xce, 0x59, 0xba, 0xae, 0x06,
	0x7b, 0xf7, 0xdf, 0xaa, 0x86, 0xad, 0xb7, 0x56, 0x43, 0xd8, 0xa5, 0x86, 0xc1, 0xdd, 0xc4, 0x0e,
	0x6f, 0x53, 0xc3, 0x29, 0x96, 0xeb, 0x09, 0x7a, 0x7e, 0x0f, 0x82, 0x9e, 0xe3, 0x8e, 0xd4, 0x5a,
	0xc7, 0x47, 0x1d, 0xfc, 0x10, 0xd8, 0xc2, 0xea, 0xed, 0xbc, 0xe3, 0x77, 0xd7, 0x04, 0xf9, 0x13,
	0x30, 0x26, 0x6d, 0x2c, 0x6c, 0xda, 0x35, 0xeb, 0x6a, 0xed, 0xf4, 0x9a, 0xf5, 0x0c, 0x3d, 0x5f,
	0xb4, 0x2c, 0x4a, 0x3e, 0x87, 0xa1, 0x90, 0xba, 0xa0, 0x5c, 0xc5, 0xbd, 0x69, 0x7f, 0xb6, 0x3d,
	0x27, 0x6d, 0xa6, 0xed, 0x52, 0xea, 0x5d, 0x12, 0x01, 0x23, 0x0f, 0x92, 0x1d, 0x08, 0x0a, 0xe6,
	0x1e, 0xc7, 0xa0, 0x60, 0xa6, 0x46, 0x5d, 0xe8, 0xd2, 0x5f, 0x0a, 0xd6, 0xc0, 0xbe, 0x48, 0xa1,
	0xb9, 0xd0, 0xfe, 0xd2, 0x72, 0xa6, 0xa9, 0x1e, 0x2f, 0xa4, 0xad, 0x69, 0xdf, 0x54, 0x6f, 0xbe,
	0x4d, 0x4c, 0x21, 0xe3, 0x10, 0x91, 0x40, 0xc8, 0xe4, 0x4f, 0x27, 0xb3, 0x63, 0x4b, 0xbc, 0x27,
	0xcc, 0x6a, 0xdb, 0x12, 0x76, 0xa5, 0x94, 0xe0, 0xad, 0x95, 0xd2, 0xef, 0x52, 0x4a, 0xe7, 0x08,
	0x06, 0xb3, 0xd0, 0x29, 0xc5, 0xc4, 0xf3, 0xaf, 0xc2, 0x00, 0xf1, 0xe6, 0x49, 0xf8, 0x35, 0x68,
	0x65, 0xff, 0xae, 0x3c, 0x09, 0xed, 0x3b, 0x22, 0xec, 0x78, 0xfc, 0x06, 0x37, 0x06, 0x76, 0x17,
	0xc2, 0x92, 0x5f, 0xf2, 0x32, 0x1e, 0x62, 0x38, 0x6b, 0xdc, 0xf6, 0xc0, 0x8c, 0x6e, 0x7b, 0x60,
	0x66, 0x96, 0x89, 0xf9, 0xd1, 0x7f, 0xbd, 0x2f, 0xc9, 0xb4, 0xe5, 0x49, 0x4d, 0xc7, 0x17, 0x65,
	0xbe, 0x74, 0x3f, 0x32, 0xf8, 0xed, 0xe5, 0x3c, 0xc7, 0xbf, 0xd1, 0xe4, 0x51, 0xcb, 0xa2, 0xe4,
	0x3d, 0xe8, 0xaf, 0xeb, 0xd2, 0xf1, 0x6a, 0x3e, 0x93, 0xdf, 0x9c, 0x84, 0xe6, 0xf3, 0x77, 0xa7,
	0x09, 0x4d, 0x09, 0x27, 0xd7, 0x4a, 0x38, 0xb9, 0xa3, 0x04, 0xff, 0x6b, 0x31, 0x7f, 0xf2, 0xff,
	0xfb, 0xb5, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xd7, 0x4a, 0xd4, 0x56, 0x0c, 0x00, 0x00,
}
