// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package go_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// --------------------------------------------------
// 获取角色信息
// --------------------------------------------------
type M_1201Tos struct {
	RoleId           *uint32 `protobuf:"varint,1,req,name=role_id,json=roleId" json:"role_id,omitempty"`
	AuthKey          []byte  `protobuf:"bytes,2,req,name=auth_key,json=authKey" json:"auth_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1201Tos) Reset()                    { *m = M_1201Tos{} }
func (m *M_1201Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1201Tos) ProtoMessage()               {}
func (*M_1201Tos) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *M_1201Tos) GetRoleId() uint32 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

func (m *M_1201Tos) GetAuthKey() []byte {
	if m != nil {
		return m.AuthKey
	}
	return nil
}

// 错误发错误协议
// 收到下面的信息，说明已有游戏名称,nickname
type M_1201Toc struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1201Toc) Reset()                    { *m = M_1201Toc{} }
func (m *M_1201Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1201Toc) ProtoMessage()               {}
func (*M_1201Toc) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

// 随机游戏名称
type M_1202Tos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1202Tos) Reset()                    { *m = M_1202Tos{} }
func (m *M_1202Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1202Tos) ProtoMessage()               {}
func (*M_1202Tos) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

type M_1202Toc struct {
	NickName         []byte `protobuf:"bytes,1,req,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1202Toc) Reset()                    { *m = M_1202Toc{} }
func (m *M_1202Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1202Toc) ProtoMessage()               {}
func (*M_1202Toc) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *M_1202Toc) GetNickName() []byte {
	if m != nil {
		return m.NickName
	}
	return nil
}

// --------------------------------------------------
// 创建角色
// --------------------------------------------------
type M_1203Tos struct {
	Name             []byte  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Icon             *string `protobuf:"bytes,2,req,name=icon" json:"icon,omitempty"`
	Gender           *uint32 `protobuf:"varint,3,req,name=gender" json:"gender,omitempty"`
	AgentId          *uint32 `protobuf:"varint,4,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Province         *uint32 `protobuf:"varint,5,opt,name=province" json:"province,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1203Tos) Reset()                    { *m = M_1203Tos{} }
func (m *M_1203Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1203Tos) ProtoMessage()               {}
func (*M_1203Tos) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *M_1203Tos) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *M_1203Tos) GetIcon() string {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return ""
}

func (m *M_1203Tos) GetGender() uint32 {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return 0
}

func (m *M_1203Tos) GetAgentId() uint32 {
	if m != nil && m.AgentId != nil {
		return *m.AgentId
	}
	return 0
}

func (m *M_1203Tos) GetProvince() uint32 {
	if m != nil && m.Province != nil {
		return *m.Province
	}
	return 0
}

// 错误发错误协议
type M_1203Toc struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1203Toc) Reset()                    { *m = M_1203Toc{} }
func (m *M_1203Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1203Toc) ProtoMessage()               {}
func (*M_1203Toc) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

// --------------------------------------------------
// 角色登入
// --------------------------------------------------
type M_1204Tos struct {
	Version          *string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1204Tos) Reset()                    { *m = M_1204Tos{} }
func (m *M_1204Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1204Tos) ProtoMessage()               {}
func (*M_1204Tos) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *M_1204Tos) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

// 错误发错误协议,发空协议则在大厅
type M_1204Toc struct {
	InGame           *bool  `protobuf:"varint,1,opt,name=in_game,json=inGame" json:"in_game,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1204Toc) Reset()                    { *m = M_1204Toc{} }
func (m *M_1204Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1204Toc) ProtoMessage()               {}
func (*M_1204Toc) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *M_1204Toc) GetInGame() bool {
	if m != nil && m.InGame != nil {
		return *m.InGame
	}
	return false
}

// 帐号异地登陆，被挤下线
type M_1206Toc struct {
	Reason           *uint32 `protobuf:"varint,1,req,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1206Toc) Reset()                    { *m = M_1206Toc{} }
func (m *M_1206Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1206Toc) ProtoMessage()               {}
func (*M_1206Toc) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *M_1206Toc) GetReason() uint32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

// 断线重连
type M_1207Tos struct {
	RoleId           *uint32 `protobuf:"varint,1,req,name=role_id,json=roleId" json:"role_id,omitempty"`
	AuthKey          []byte  `protobuf:"bytes,2,req,name=auth_key,json=authKey" json:"auth_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1207Tos) Reset()                    { *m = M_1207Tos{} }
func (m *M_1207Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1207Tos) ProtoMessage()               {}
func (*M_1207Tos) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *M_1207Tos) GetRoleId() uint32 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

func (m *M_1207Tos) GetAuthKey() []byte {
	if m != nil {
		return m.AuthKey
	}
	return nil
}

type M_1207Toc struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *M_1207Toc) Reset()                    { *m = M_1207Toc{} }
func (m *M_1207Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1207Toc) ProtoMessage()               {}
func (*M_1207Toc) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

// 协议测试
type M_1208Tos struct {
	ToServer         *string `protobuf:"bytes,1,req,name=to_server,json=toServer" json:"to_server,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1208Tos) Reset()                    { *m = M_1208Tos{} }
func (m *M_1208Tos) String() string            { return proto.CompactTextString(m) }
func (*M_1208Tos) ProtoMessage()               {}
func (*M_1208Tos) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *M_1208Tos) GetToServer() string {
	if m != nil && m.ToServer != nil {
		return *m.ToServer
	}
	return ""
}

// 错误发错误协议,发空协议则在大厅
type M_1208Toc struct {
	ToClient         *string `protobuf:"bytes,1,req,name=to_client,json=toClient" json:"to_client,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M_1208Toc) Reset()                    { *m = M_1208Toc{} }
func (m *M_1208Toc) String() string            { return proto.CompactTextString(m) }
func (*M_1208Toc) ProtoMessage()               {}
func (*M_1208Toc) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *M_1208Toc) GetToClient() string {
	if m != nil && m.ToClient != nil {
		return *m.ToClient
	}
	return ""
}

func init() {
	proto.RegisterType((*M_1201Tos)(nil), "go_proto.m_1201_tos")
	proto.RegisterType((*M_1201Toc)(nil), "go_proto.m_1201_toc")
	proto.RegisterType((*M_1202Tos)(nil), "go_proto.m_1202_tos")
	proto.RegisterType((*M_1202Toc)(nil), "go_proto.m_1202_toc")
	proto.RegisterType((*M_1203Tos)(nil), "go_proto.m_1203_tos")
	proto.RegisterType((*M_1203Toc)(nil), "go_proto.m_1203_toc")
	proto.RegisterType((*M_1204Tos)(nil), "go_proto.m_1204_tos")
	proto.RegisterType((*M_1204Toc)(nil), "go_proto.m_1204_toc")
	proto.RegisterType((*M_1206Toc)(nil), "go_proto.m_1206_toc")
	proto.RegisterType((*M_1207Tos)(nil), "go_proto.m_1207_tos")
	proto.RegisterType((*M_1207Toc)(nil), "go_proto.m_1207_toc")
	proto.RegisterType((*M_1208Tos)(nil), "go_proto.m_1208_tos")
	proto.RegisterType((*M_1208Toc)(nil), "go_proto.m_1208_toc")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x95, 0x52, 0xf2, 0xc7, 0xb4, 0x8b, 0x87, 0x62, 0xe8, 0x12, 0x45, 0x80, 0xc2, 0x82,
	0x68, 0x8b, 0x28, 0x23, 0x12, 0x03, 0xaa, 0x90, 0x18, 0xcc, 0x07, 0xb0, 0x22, 0xe7, 0x14, 0xac,
	0xb6, 0x76, 0xe5, 0x98, 0x4a, 0x9d, 0xf9, 0xe2, 0xc8, 0x97, 0x34, 0x84, 0x99, 0xed, 0x7e, 0xf6,
	0xd3, 0xd3, 0x7b, 0x77, 0xe4, 0x6c, 0x63, 0x2a, 0xa5, 0xef, 0x76, 0xd6, 0x38, 0x43, 0xe3, 0xca,
	0x08, 0x9c, 0xb2, 0x67, 0x42, 0xb6, 0x62, 0x36, 0xbf, 0x9f, 0x09, 0x67, 0x6a, 0x7a, 0x4e, 0x22,
	0x6b, 0x36, 0x20, 0x54, 0xc9, 0x82, 0x74, 0x90, 0x8f, 0x79, 0xe8, 0x71, 0x55, 0xd2, 0x0b, 0x12,
	0x17, 0x5f, 0xee, 0x53, 0xac, 0xe1, 0xc0, 0x06, 0xe9, 0x20, 0x1f, 0xf1, 0xc8, 0xf3, 0x1b, 0x1c,
	0xb2, 0x51, 0xcf, 0x41, 0x76, 0x34, 0xf7, 0x7e, 0xd9, 0x6d, 0x8f, 0x24, 0x9d, 0x92, 0x44, 0x2b,
	0xb9, 0x16, 0xba, 0xd8, 0x02, 0xfa, 0x8f, 0x78, 0xec, 0x1f, 0xde, 0x8b, 0x2d, 0x64, 0xdf, 0x41,
	0xab, 0x5d, 0x60, 0x12, 0x4a, 0x86, 0x3d, 0x19, 0xce, 0xfe, 0x4d, 0x49, 0xa3, 0x31, 0x40, 0xc2,
	0x71, 0xa6, 0x13, 0x12, 0x56, 0xa0, 0x4b, 0xb0, 0xec, 0xa4, 0x09, 0xdc, 0x10, 0x06, 0xae, 0x40,
	0x3b, 0x5f, 0x65, 0x98, 0x06, 0xf9, 0x98, 0x47, 0xc8, 0xab, 0x92, 0x5e, 0x92, 0x78, 0x67, 0xcd,
	0x5e, 0x69, 0x09, 0xec, 0x14, 0xbf, 0x3a, 0xee, 0xe2, 0x2f, 0xb0, 0xcc, 0x4d, 0x4b, 0x0f, 0x18,
	0x89, 0x91, 0x68, 0x0f, 0xb6, 0x56, 0x46, 0xb3, 0x20, 0x0d, 0xf2, 0x84, 0x1f, 0x31, 0xbb, 0xee,
	0xe9, 0xa4, 0x5f, 0xa2, 0xd2, 0xa2, 0x6a, 0xd2, 0x07, 0x79, 0xcc, 0x43, 0xa5, 0x5f, 0x7d, 0xc5,
	0xab, 0x56, 0xf6, 0x88, 0xb2, 0x09, 0x09, 0x2d, 0x14, 0x35, 0xba, 0x35, 0xab, 0x46, 0xea, 0x2e,
	0xb2, 0xfc, 0xf7, 0x45, 0x96, 0x58, 0xe2, 0x78, 0x83, 0x27, 0xf4, 0x9b, 0x92, 0xc4, 0x19, 0x51,
	0x83, 0xdd, 0x83, 0x45, 0xc7, 0x84, 0xc7, 0xce, 0x7c, 0x20, 0xff, 0x91, 0xca, 0x56, 0x2a, 0x37,
	0x0a, 0xb4, 0xfb, 0x95, 0xbe, 0x20, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xa7, 0x02, 0x50,
	0x4f, 0x02, 0x00, 0x00,
}
