// !!! DO NOT EDIT !!!
// auto generated from Excel files
package go_config

import(
	"test/go_include"
	"test/go_log"
)

func Cfg_hu_rate(key uint32) (go_include.Cfg_hu_rate) {
	var cfg_hu_rate = map[uint32]go_include.Cfg_hu_rate{
		1:
			go_include.Cfg_hu_rate{
				Type:1,
				Rate:1,
				Min_gen:0,
			},
		2:
			go_include.Cfg_hu_rate{
				Type:2,
				Rate:2,
				Min_gen:0,
			},
		3:
			go_include.Cfg_hu_rate{
				Type:3,
				Rate:4,
				Min_gen:0,
			},
		4:
			go_include.Cfg_hu_rate{
				Type:4,
				Rate:4,
				Min_gen:0,
			},
		5:
			go_include.Cfg_hu_rate{
				Type:5,
				Rate:4,
				Min_gen:0,
			},
		6:
			go_include.Cfg_hu_rate{
				Type:6,
				Rate:4,
				Min_gen:0,
			},
		7:
			go_include.Cfg_hu_rate{
				Type:7,
				Rate:8,
				Min_gen:0,
			},
		8:
			go_include.Cfg_hu_rate{
				Type:8,
				Rate:8,
				Min_gen:0,
			},
		9:
			go_include.Cfg_hu_rate{
				Type:9,
				Rate:8,
				Min_gen:1,
			},
		10:
			go_include.Cfg_hu_rate{
				Type:10,
				Rate:16,
				Min_gen:0,
			},
		11:
			go_include.Cfg_hu_rate{
				Type:11,
				Rate:16,
				Min_gen:0,
			},
		12:
			go_include.Cfg_hu_rate{
				Type:12,
				Rate:16,
				Min_gen:0,
			},
		13:
			go_include.Cfg_hu_rate{
				Type:13,
				Rate:16,
				Min_gen:0,
			},
		14:
			go_include.Cfg_hu_rate{
				Type:14,
				Rate:32,
				Min_gen:0,
			},
		15:
			go_include.Cfg_hu_rate{
				Type:15,
				Rate:32,
				Min_gen:0,
			},
		16:
			go_include.Cfg_hu_rate{
				Type:16,
				Rate:32,
				Min_gen:1,
			},
		17:
			go_include.Cfg_hu_rate{
				Type:17,
				Rate:64,
				Min_gen:4,
			},
		18:
			go_include.Cfg_hu_rate{
				Type:18,
				Rate:256,
				Min_gen:4,
			},
	}
	if result, ok := cfg_hu_rate[key]; ok {
		return result
	}
	go_log.Error("Cfg_hu_rate not match:", key)
	return go_include.Cfg_hu_rate{}
}